# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "headers", :force => true do |t|
    t.column "request_id", :integer,                :default => 0,  :null => false
    t.column "name",       :string,  :limit => nil, :default => "", :null => false
    t.column "domain",     :text,                   :default => ""
  end

  create_table "requests", :force => true do |t|
    t.column "http_method", :string,  :limit => 10, :default => "", :null => false
    t.column "path",        :text,                  :default => "", :null => false
    t.column "weight",      :integer,               :default => 0,  :null => false
    t.column "remarks",     :text,                  :default => ""
  end

end
