#!/bin/sh -e
#
# apache2 start/stop script
#
# Now this is really simple.
#

BINARY=/usr/sbin/apache2
CONF=`pwd`/httpd.conf

pidof_apache() {
	if [ -f ./httpd.pid ]; then
		PID=`cat ./httpd.pid`
	else
		echo "PID file not found. Aborting."
		exit 1
	fi

}

case $1 in
	start)
		$BINARY -f $CONF
		sleep 1
	;;
	stop)
		$BINARY -k stop -f $CONF
		sleep 1
		if [ -f httpd.pid ]; then
			rm httpd.pid
		fi
	;;
	restart)
		pidof_apache
		kill $PID
		sleep 1
		$BINARY -f $CONF
	;;
esac
